### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by danielklecha** [jstedfast/MimeKit#1167]
Hi!

My project is using strong-named assemblies.
Could you modify the deployment to generate two versions of the package?
For example:
- MimeKitLite and MimeKitLite.StrongName
- MimeKit and MimeKit.StrongName
Do you have plans to do that?

If you need to generate an SNK file, you can follow these steps:
1. Open the Visual Studio Developer Command Prompt
2. Run the following command: `sn -k MimeKit.snk`
3. Store the generated file in a safe place.
4. If you need to use it with GitHub Actions as a secret, you can generate a base64 version with the following PowerShell command: `[Convert]::ToBase64String([IO.File]::ReadAllBytes('MimeKit.snk'))`

I use GitHub actions for my library, and steps similar to those below should work for your library.

```yaml
    - name: Create Strong Name Assembly Key File for MimeKit
      run: |
        echo "${{ secrets.STRONG_NAME_KEY_MIMEKIT }}" | base64 --decode > MimeKit.snk

    - name: Create Strong Name Assembly Key File for MimeKitLite
      run: |
        echo "${{ secrets.STRONG_NAME_KEY_MIMEKITLITE }}" | base64 --decode > MimeKitLite.snk

    - name: Build MimeKit (Strong-Named)
      run: dotnet build MimeKit/MimeKit.csproj --configuration Release --no-restore /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$PWD/MimeKit.snk

    - name: Pack MimeKit (Strong-Named)
      run: dotnet pack MimeKit/MimeKit.csproj --configuration Release --no-build /p:PackageId=MimeKit.StrongName

    - name: Build MimeKitLite (Strong-Named)
      run: dotnet build MimeKit/MimeKitLite.csproj --configuration Release --no-restore /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$PWD/MimeKitLite.snk

    - name: Pack MimeKitLite (Strong-Named)
      run: dotnet pack MimeKit/MimeKitLite.csproj --configuration Release --no-build /p:PackageId=MimeKitLite.StrongName

    - name: Publish to NuGet
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }}
```

Best regards
